#include <switch.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <dirent.h>
#include <sys/stat.h>
#include <errno.h>

#include "net.h"
#include "iarchive.h"
#include "fsutil.h"
#include "jsonutil.h"
#include "config.h"
#include "extract.h"
#include "update.h"
#include "queue.h"
#include "version.h" /* generated by bump_version.sh: defines APP_VERSION_STR */

#ifndef APP_VERSION_STR
#define APP_VERSION_STR "0.0.0"
#endif

/* DL_TMP_DIR / ROMS_ROOT are defined in config.h (shared with the queue). */

static PadState g_pad;
static SourcesConfig g_cfg;
static Credentials g_creds;
static Prefs g_prefs;
static char g_self_path[1024]; /* path to our own .nro, for self-update */

/* Global toast: a short confirmation/error message drawn on the footer row by
 * draw_footer for a couple of seconds, set from anywhere via toast()/toast_err(). */
static char g_toast[160];
static int g_toast_t;
static bool g_toast_err;

static void toast_v(bool err, const char *fmt, va_list ap) {
    vsnprintf(g_toast, sizeof(g_toast), fmt, ap);
    g_toast_err = err;
    g_toast_t = 150; /* ~2.5s at 60fps */
}
static void toast(const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    toast_v(false, fmt, ap);
    va_end(ap);
}
static void toast_error(const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    toast_v(true, fmt, ap);
    va_end(ap);
}

/* ---- small helpers --------------------------------------------------- */

static void wait_for_button(void) {
    printf("\nPress B to continue.\n");
    consoleUpdate(NULL);
    while (appletMainLoop()) {
        padUpdate(&g_pad);
        if (padGetButtonsDown(&g_pad) & (HidNpadButton_B | HidNpadButton_A)) {
            break;
        }
        consoleUpdate(NULL);
    }
}

static bool prompt_text(const char *guide, const char *initial, char *out,
                        size_t out_sz) {
    SwkbdConfig kbd;
    if (R_FAILED(swkbdCreate(&kbd, 0))) {
        return false;
    }
    swkbdConfigMakePresetDefault(&kbd);
    if (guide) {
        swkbdConfigSetGuideText(&kbd, guide);
    }
    if (initial) {
        swkbdConfigSetInitialText(&kbd, initial);
    }
    Result rc = swkbdShow(&kbd, out, out_sz);
    swkbdClose(&kbd);
    return R_SUCCEEDED(rc) && out[0] != '\0';
}

static void human_size(uint64_t bytes, char *out, size_t out_sz) {
    const char *unit[] = {"B", "KB", "MB", "GB", "TB"};
    double v = (double)bytes;
    int u = 0;
    while (v >= 1024.0 && u < 4) {
        v /= 1024.0;
        u++;
    }
    snprintf(out, out_sz, "%.1f %s", v, unit[u]);
}

/* Navigation with key-repeat. Returns -1 (up), +1 (down), or 0. *hold tracks
 * how many frames a direction has been held so we can auto-repeat. */
static int nav_repeat(u64 kDown, u64 kHeld, int *hold) {
    const int DELAY = 20; /* frames held before auto-repeat kicks in (~0.33s) */
    const int RATE = 2;   /* then move every RATE frames */
    if (kDown & HidNpadButton_AnyUp) {
        *hold = 0;
        return -1;
    }
    if (kDown & HidNpadButton_AnyDown) {
        *hold = 0;
        return 1;
    }
    if (kHeld & (HidNpadButton_AnyUp | HidNpadButton_AnyDown)) {
        (*hold)++;
        if (*hold > DELAY && ((*hold - DELAY) % RATE) == 0) {
            return (kHeld & HidNpadButton_AnyDown) ? 1 : -1;
        }
        return 0;
    }
    *hold = 0;
    return 0;
}

static int con_width(void) {
    PrintConsole *con = consoleGetDefault();
    return con ? con->consoleWidth : 80;
}
static int con_height(void) {
    PrintConsole *con = consoleGetDefault();
    return con ? con->consoleHeight : 45;
}

/* ANSI/SGR colors (libnx console supports these). Kept to the widely-supported
 * 30-37 / 40-47 set plus bold(1) so they render on the Switch console. */
#define C_RESET  "\x1b[0m"
#define C_HDR    "\x1b[1;37;44m" /* bold white on blue (header bar) */
#define C_FOOT   "\x1b[30;107m"  /* black on bright/pure white (footer bar) */
#define C_SEL    "\x1b[1;36m"    /* bold cyan (accent) */
#define C_SELROW "\x1b[30;46m"   /* black on cyan: full-width selected-row bar */
#define C_WHITE  "\x1b[97m"      /* bright white (default fg renders greyish) */
#define C_CYAN   "\x1b[36m"
#define C_GREEN  "\x1b[32m"
#define C_YELLOW "\x1b[33m"
#define C_RED    "\x1b[31m"
#define C_ALERT  "\x1b[1;37;42m" /* bold bright-white on green (toast) */
#define C_ERR    "\x1b[1;37;41m" /* bold white on red (error toast) */

/* Rows available for a list: header bar (row 1) + blank (row 2) + content +
 * blank (row h-2) + activity (row h-1) + footer (row h). */
static int list_rows(void) {
    int r = con_height() - 5;
    return r > 1 ? r : 1;
}

/* Color a byte size by magnitude: KB green, MB yellow, GB+ red, bytes default. */
static const char *size_color(uint64_t b) {
    if (b >= (1ULL << 30)) return C_RED;
    if (b >= (1ULL << 20)) return C_YELLOW;
    if (b >= (1ULL << 10)) return C_GREEN;
    return "";
}

/* Free space on the SD card, re-checked at most every ~2s (statvfs isn't free,
 * and the header redraws every frame). */
static uint64_t sd_free_cached(void) {
    static uint64_t cached = 0;
    static uint64_t last_tick = 0;
    static bool init = false;
    uint64_t now = armGetSystemTick();
    if (!init || armTicksToNs(now - last_tick) > 2000000000ULL) {
        cached = fs_free_bytes("sdmc:/");
        last_tick = now;
        init = true;
    }
    return cached;
}

/* Battery charge percentage, refreshed at most every ~5s (battery moves slowly
 * and each read is a service IPC call). Requires psmInitialize() in main(). */
static u32 battery_cached(void) {
    static u32 cached = 0;
    static uint64_t last_tick = 0;
    static bool init = false;
    uint64_t now = armGetSystemTick();
    if (!init || armTicksToNs(now - last_tick) > 5000000000ULL) {
        u32 pct = 0;
        if (R_SUCCEEDED(psmGetBatteryChargePercentage(&pct))) {
            cached = pct;
        }
        last_tick = now;
        init = true;
    }
    return cached;
}

/* Blue header bar on row 1 (title + subtitle left, SD free right); leaves the
 * cursor at row 3 (row 2 stays blank). */
static void draw_header(const char *subtitle) {
    consoleClear();
    int w = con_width() - 1;

    char left[256];
    if (subtitle && subtitle[0]) {
        snprintf(left, sizeof(left), " TicoDL+   %s", subtitle);
    } else {
        snprintf(left, sizeof(left), " TicoDL+");
    }

    /* Build a width-w bar so we can right-align the SD readout into it. */
    char bar[256];
    if (w > (int)sizeof(bar) - 1) {
        w = sizeof(bar) - 1;
    }
    memset(bar, ' ', w);
    bar[w] = '\0';
    int ll = (int)strlen(left);
    if (ll > w) {
        ll = w;
    }
    memcpy(bar, left, ll);

    uint64_t freeb = sd_free_cached();
    char hf[24];
    if (freeb == UINT64_MAX) {
        snprintf(hf, sizeof(hf), "?");
    } else {
        human_size(freeb, hf, sizeof(hf));
    }
    char fr[64];
    snprintf(fr, sizeof(fr), "SD %s   %u%% ", hf, (unsigned)battery_cached());
    int fl = (int)strlen(fr);
    if (fl <= w - ll - 2) { /* only if it won't collide with the subtitle */
        memcpy(bar + (w - fl), fr, fl);
    }

    printf("\x1b[1;1H" C_HDR "%s" C_RESET "\x1b[3;1H", bar);
}

/* Draw a full-width colored bar at the given (1-based) row. */
static void draw_bar(int row, const char *color, const char *text) {
    int w = con_width() - 1;
    printf("\x1b[%d;1H%s%-*.*s" C_RESET, row, color, w, w, text);
}

/* One-line summary of the in-progress download, drawn in the blank row just
 * above the footer. Nothing is drawn when the queue is idle (the row stays
 * blank, since draw_header clears the screen each frame). */
static void draw_activity(void) {
    char nm[512];
    QStatus st;
    uint64_t now = 0, total = 0, speed = 0;
    int idx = 0, cnt = 0;
    if (!queue_active_info(nm, sizeof(nm), &st, &now, &total, &speed, &idx,
                           &cnt)) {
        return;
    }
    const char *verb = (st == Q_DOWNLOADING)  ? "DL"
                       : (st == Q_VERIFYING)  ? "VERIFY"
                                              : "UNZIP";
    char info[48] = "";
    if (st == Q_DOWNLOADING && total) {
        char ht[16];
        human_size(total, ht, sizeof(ht));
        if (speed) {
            char hsp[16];
            human_size(speed, hsp, sizeof(hsp));
            snprintf(info, sizeof(info), "  %d%% of %s @ %s/s",
                     (int)((now * 100) / total), ht, hsp);
        } else {
            snprintf(info, sizeof(info), "  %d%% of %s",
                     (int)((now * 100) / total), ht);
        }
    }
    char line[256];
    snprintf(line, sizeof(line), " %s %d/%d: %.40s%s", verb, idx, cnt, nm, info);
    draw_bar(con_height() - 1, C_FOOT, line);
}

/* Footer bar pinned to the last row: controls, or a transient toast message.
 * Also draws the active-download line on the row above it. */
static void draw_footer(const char *controls) {
    draw_activity();
    char line[256];
    if (g_toast_t > 0) {
        snprintf(line, sizeof(line), " %s", g_toast);
        draw_bar(con_height(), g_toast_err ? C_ERR : C_ALERT, line);
        g_toast_t--;
        return;
    }
    snprintf(line, sizeof(line), " %s", controls);
    draw_bar(con_height(), C_FOOT, line);
}

/* Render a selected list row as a full-width highlight bar. `plain` is the row
 * text with no embedded color codes (truncated/padded to the screen width). */
static void hl_row(const char *plain) {
    int w = con_width() - 1;
    printf(C_SELROW "%-*.*s" C_RESET "\n", w, w, plain);
}

/* Thin vertical scrollbar in the last column over the content rows (3..h-2).
 * `first` = index of the first visible row, `total` = item count. No-op when
 * everything already fits on one screen. Safe in the last column because it
 * never draws on the bottom row (only the bottom row scrolls on edge-write). */
static void draw_scrollbar(int first, int total) {
    int track = list_rows();
    if (total <= track || track < 2) {
        return;
    }
    int col = con_width();
    int thumb = track * track / total;
    if (thumb < 1) {
        thumb = 1;
    }
    if (thumb > track - 1) {
        thumb = track - 1;
    }
    int span = track - thumb;
    int maxfirst = total - track;
    int pos = maxfirst > 0 ? (int)((long)span * first / maxfirst) : 0;
    if (pos < 0) {
        pos = 0;
    }
    if (pos > span) {
        pos = span;
    }
    for (int i = 0; i < track; i++) {
        bool on = (i >= pos && i < pos + thumb);
        printf("\x1b[%d;%dH%s%c" C_RESET, 3 + i, col, on ? C_GREEN : C_CYAN,
               on ? '#' : '|');
    }
}


/* ---- download -------------------------------------------------------- */

struct prog_state {
    int last_pct;
};

static int progress_cb(void *ud, uint64_t now, uint64_t total) {
    struct prog_state *ps = (struct prog_state *)ud;
    padUpdate(&g_pad);
    if (padGetButtonsDown(&g_pad) & HidNpadButton_B) {
        return 1; /* abort */
    }
    int pct = total ? (int)((now * 100) / total) : -1;
    if (pct != ps->last_pct) {
        ps->last_pct = pct;
        char hn[32], ht[32];
        human_size(now, hn, sizeof(hn));
        human_size(total, ht, sizeof(ht));
        if (pct >= 0) {
            printf("\r  %3d%%  %s / %s        ", pct, hn, ht);
        } else {
            printf("\r  %s downloaded        ", hn);
        }
        consoleUpdate(NULL);
    }
    return 0;
}

/* Keep the console awake while downloads are active, if the user enabled it.
 * Called from the UI loops (applet calls must stay on the main thread). */
static void applet_sleep_tick(void) {
    static bool cur = false;
    bool want = g_prefs.prevent_sleep && (queue_active_count() > 0);
    if (want != cur) {
        appletSetMediaPlaybackState(want);
        cur = want;
    }
}

/* Enqueue a file for background download into tico/roms/<target>. */
static bool enqueue_file(const ArchiveItem *item, const ArchiveFile *file,
                         const char *target) {
    char url[1024];
    ia_file_url(item, file, url, sizeof(url));
    char auth[320];
    creds_auth_header(&g_creds, auth, sizeof(auth));
    return queue_add(url, file->name, target, auth, file->size,
                     is_archive_name(file->name), file->md5);
}

/* ---- file picker for one fetched item -------------------------------- */

/* How a browse screen was left: back to menu, switch console, or force a
 * fresh metadata download of the current console. */
typedef enum { BR_BACK, BR_PREV, BR_NEXT, BR_REFRESH } BrowseResult;

/* A simple branded message screen that still allows console switching. */
static BrowseResult browse_message(const char *target, const char *line1,
                                   const char *line2) {
    while (appletMainLoop()) {
        char sub[64];
        snprintf(sub, sizeof(sub), "[%s]", target);
        draw_header(sub);
        printf("L/R console   X refresh   B back\n\n");
        printf("%s\n", line1);
        if (line2) {
            printf("%s\n", line2);
        }
        consoleUpdate(NULL);
        applet_sleep_tick();
        padUpdate(&g_pad);
        u64 k = padGetButtonsDown(&g_pad);
        if (k & HidNpadButton_B) {
            return BR_BACK;
        }
        if (k & HidNpadButton_L) {
            return BR_PREV;
        }
        if (k & HidNpadButton_R) {
            return BR_NEXT;
        }
        if (k & HidNpadButton_X) {
            return BR_REFRESH;
        }
    }
    return BR_BACK;
}

/* Case-insensitive substring test (empty needle matches everything). */
static bool ci_contains(const char *hay, const char *needle) {
    if (!needle[0]) {
        return true;
    }
    size_t nl = strlen(needle);
    for (const char *p = hay; *p; p++) {
        if (strncasecmp(p, needle, nl) == 0) {
            return true;
        }
    }
    return false;
}

/* Snapshot of the immediate entry names in a directory, for membership checks
 * (used to flag files that are already installed under tico/roms/<target>). */
typedef struct {
    char (*names)[256];
    int count;
} NameList;

static void namelist_load(const char *dir, NameList *nl) {
    nl->names = NULL;
    nl->count = 0;
    DIR *d = opendir(dir);
    if (!d) {
        return;
    }
    int cap = 64, cnt = 0;
    char (*arr)[256] = (char (*)[256])malloc((size_t)256 * cap);
    if (!arr) {
        closedir(d);
        return;
    }
    struct dirent *e;
    while ((e = readdir(d)) != NULL) {
        if (!strcmp(e->d_name, ".") || !strcmp(e->d_name, "..")) {
            continue;
        }
        if (cnt >= cap) {
            cap *= 2;
            char (*na)[256] = (char (*)[256])realloc(arr, (size_t)256 * cap);
            if (!na) {
                break;
            }
            arr = na;
        }
        snprintf(arr[cnt], 256, "%s", e->d_name);
        cnt++;
    }
    closedir(d);
    nl->names = arr;
    nl->count = cnt;
}

static void namelist_free(NameList *nl) {
    free(nl->names);
    nl->names = NULL;
    nl->count = 0;
}

/* True if `file` appears already installed: an exact (case-insensitive) match,
 * or — for archives — an installed entry starting with the archive's base name
 * (e.g. "Game.zip" already extracted to "Game.sfc" or a "Game/" folder). */
static bool name_installed(const NameList *nl, const char *file) {
    for (int i = 0; i < nl->count; i++) {
        if (strcasecmp(nl->names[i], file) == 0) {
            return true;
        }
    }
    if (!is_archive_name(file)) {
        return false;
    }
    char base[512];
    snprintf(base, sizeof(base), "%s", file);
    char *dot = strrchr(base, '.');
    if (dot && dot != base) {
        *dot = '\0';
    }
    size_t bl = strlen(base);
    if (bl == 0) {
        return false;
    }
    for (int i = 0; i < nl->count; i++) {
        if (strncasecmp(nl->names[i], base, bl) == 0) {
            return true;
        }
    }
    return false;
}

static BrowseResult browse_item(ArchiveItem *item, const char *target,
                                const char *crumb) {
    int cursor = 0;
    int top = 0;
    int hold = 0;
    const int rows = list_rows();
    char filter[64] = "";

    /* fidx maps visible rows -> indices into item->files (for the name filter).*/
    int total = item->file_count;
    int *fidx = (int *)malloc(sizeof(int) * (total > 0 ? total : 1));
    if (!fidx) {
        return BR_BACK;
    }
    int fn = 0;
    for (int i = 0; i < total; i++) {
        fidx[fn++] = i;
    }

    /* Flag files already present under tico/roms/<target> (computed once on
     * entry; re-entering the list — e.g. after X refresh — recomputes it). */
    NameList inst_nl;
    char rdir[1200];
    snprintf(rdir, sizeof(rdir), "%s/%s", ROMS_ROOT, target);
    namelist_load(rdir, &inst_nl);
    unsigned char *inst = (unsigned char *)calloc(total > 0 ? total : 1, 1);
    if (inst) {
        for (int i = 0; i < total; i++) {
            inst[i] = name_installed(&inst_nl, item->files[i].name) ? 1 : 0;
        }
    }
    namelist_free(&inst_nl);

    BrowseResult result = BR_BACK;
    bool done = false;
    while (!done && appletMainLoop() && total > 0) {
        char sub[140];
        int pos = fn > 0 ? cursor + 1 : 0;
        if (filter[0]) {
            snprintf(sub, sizeof(sub), "%.60s  (%d/%d)  filter:%.12s", crumb,
                     pos, fn, filter);
        } else {
            snprintf(sub, sizeof(sub), "%.60s  (%d/%d files)", crumb, pos, fn);
        }
        draw_header(sub);

        if (fn == 0) {
            printf(C_CYAN "  No files match \"%s\".  (Y to change filter)" C_RESET
                          "\n",
                   filter);
        }
        if (cursor >= fn) {
            cursor = fn > 0 ? fn - 1 : 0;
        }
        if (cursor < top) {
            top = cursor;
        }
        if (cursor >= top + rows) {
            top = cursor - rows + 1;
        }
        int namew = con_width() - 15; /* extra column for the installed mark */
        if (namew < 10) {
            namew = 10;
        }
        for (int i = top; i < fn && i < top + rows; i++) {
            int fi = fidx[i];
            bool sel = (i == cursor);
            bool got = inst && inst[fi];
            uint64_t sz = item->files[fi].size;
            char hs[32];
            human_size(sz, hs, sizeof(hs));
            if (sel) {
                char line[256];
                snprintf(line, sizeof(line), "%c%c %-*.*s %10s", '>',
                         got ? '*' : ' ', namew, namew, item->files[fi].name, hs);
                hl_row(line);
            } else {
                printf(" %s%c%s %-*.*s %s%10s%s\n", got ? C_GREEN : "",
                       got ? '*' : ' ', C_RESET, namew, namew,
                       item->files[fi].name, size_color(sz), hs, C_RESET);
            }
        }
        draw_scrollbar(top, fn);
        draw_footer("U/D move  ZL/ZR page  L/R repo  Y filter  X refresh  "
                    "A queue  B back");
        consoleUpdate(NULL);
        applet_sleep_tick();

        padUpdate(&g_pad);
        u64 kd = padGetButtonsDown(&g_pad);
        u64 kh = padGetButtons(&g_pad);
        if (kd & HidNpadButton_B) {
            result = BR_BACK;
            break;
        }
        if (kd & HidNpadButton_L) {
            result = BR_PREV;
            break;
        }
        if (kd & HidNpadButton_R) {
            result = BR_NEXT;
            break;
        }
        if (kd & HidNpadButton_X) {
            result = BR_REFRESH;
            break;
        }
        if (kd & HidNpadButton_Y) {
            /* Inline swkbd so an empty submit is accepted (= clear filter). */
            char f[64];
            SwkbdConfig kbd;
            if (R_SUCCEEDED(swkbdCreate(&kbd, 0))) {
                swkbdConfigMakePresetDefault(&kbd);
                swkbdConfigSetGuideText(&kbd, "Filter by name (blank = all)");
                swkbdConfigSetInitialText(&kbd, filter);
                swkbdConfigSetStringLenMax(&kbd, sizeof(filter) - 1);
                if (R_SUCCEEDED(swkbdShow(&kbd, f, sizeof(f)))) {
                    snprintf(filter, sizeof(filter), "%s", f);
                    fn = 0;
                    for (int i = 0; i < total; i++) {
                        if (ci_contains(item->files[i].name, filter)) {
                            fidx[fn++] = i;
                        }
                    }
                    cursor = 0;
                    top = 0;
                }
                swkbdClose(&kbd);
            }
            continue;
        }
        if (fn > 0) {
            int d = nav_repeat(kd, kh, &hold);
            if (d < 0) {
                cursor = (cursor - 1 + fn) % fn;
            }
            if (d > 0) {
                cursor = (cursor + 1) % fn;
            }
            if (kd & HidNpadButton_ZL) {
                cursor -= rows;
                if (cursor < 0) {
                    cursor = 0;
                }
            }
            if (kd & HidNpadButton_ZR) {
                cursor += rows;
                if (cursor >= fn) {
                    cursor = fn - 1;
                }
            }
            if (kd & HidNpadButton_A) {
                int fi = fidx[cursor];
                uint64_t sz = item->files[fi].size;
                uint64_t freeb = fs_free_bytes("sdmc:/");
                if (sz > 0 && freeb < sz) {
                    char hn[16], hf[16];
                    human_size(sz, hn, sizeof(hn));
                    human_size(freeb, hf, sizeof(hf));
                    toast_error("Not enough space: need %s, free %s", hn, hf);
                } else if (enqueue_file(item, &item->files[fi], target)) {
                    toast("Queued: %.40s   (ZL to view)", item->files[fi].name);
                } else {
                    toast_error("Queue is full");
                }
            }
        }
    }
    free(fidx);
    free(inst);
    return result;
}

/* A selectable menu entry: console ci, repo ri (ri == -1 means the console
 * group itself, used by the grouped main view). */
typedef struct {
    int ci;
    int ri;
} MenuRef;

/* Browse a list of repos (each ref must have ri >= 0), with L/R hopping between
 * them and X re-fetching. Used by the flat main list and the console screen. */
static void browse_repo_refs(const MenuRef *refs, int count, int idx) {
    bool force = false; /* set by BR_REFRESH to bypass the cache once */
    while (appletMainLoop() && count > 0) {
        ConsoleGroup *g = &g_cfg.consoles[refs[idx].ci];
        Repo *rp = &g->repos[refs[idx].ri];
        bool use_cache = g_prefs.use_cache && !force;
        force = false;
        BrowseResult r;

        if (!rp->id[0]) {
            r = browse_message(g->target, "No archive id set for this repo.",
                               "Edit it (X) to set one.");
        } else {
            char sub[96];
            snprintf(sub, sizeof(sub), "[%s] %.40s", g->target, rp->label);
            draw_header(sub);
            printf("\n%s metadata (%s)...\n", use_cache ? "Loading" : "Refreshing",
                   rp->id);
            consoleUpdate(NULL);

            ArchiveItem item;
            if (!ia_fetch(rp->id, &item, use_cache, CACHE_DIR)) {
                r = browse_message(g->target, "Metadata fetch failed,",
                                   "or item has no files. (X to retry)");
            } else {
                snprintf(item.download_base, sizeof(item.download_base), "%s",
                         rp->download_base);
                char crumb[96];
                snprintf(crumb, sizeof(crumb), "%s > %.40s", g->console,
                         rp->label);
                r = browse_item(&item, g->target, crumb);
                ia_free(&item);
            }
        }

        if (r == BR_BACK) {
            return;
        }
        if (r == BR_REFRESH) {
            force = true; /* re-fetch the same repo, ignoring cache */
            continue;
        }
        if (r == BR_NEXT) {
            idx = (idx + 1) % count;
        } else {
            idx = (idx - 1 + count) % count;
        }
    }
}

/* ---- installed (Tico) browser: read-only view of sdmc:/tico/roms ----- */

typedef struct {
    char name[256];
    bool is_dir;
    uint64_t size;
    int child_count; /* for dirs: number of immediate entries */
} DirEntry;

/* Count immediate entries (files + folders) in a directory. */
static int count_dir(const char *path) {
    DIR *d = opendir(path);
    if (!d) {
        return 0;
    }
    int c = 0;
    struct dirent *e;
    while ((e = readdir(d)) != NULL) {
        if (strcmp(e->d_name, ".") && strcmp(e->d_name, "..")) {
            c++;
        }
    }
    closedir(d);
    return c;
}

static int cmp_entries(const void *a, const void *b) {
    const DirEntry *x = a, *y = b;
    if (x->is_dir != y->is_dir) {
        return x->is_dir ? -1 : 1; /* directories first */
    }
    return strcasecmp(x->name, y->name);
}

/* Read a directory into a malloc'd, sorted array. Returns count or -1. */
static int read_dir(const char *path, DirEntry **out) {
    *out = NULL;
    DIR *d = opendir(path);
    if (!d) {
        return -1;
    }
    int cap = 64, cnt = 0;
    DirEntry *arr = (DirEntry *)malloc(sizeof(DirEntry) * cap);
    if (!arr) {
        closedir(d);
        return -1;
    }
    struct dirent *e;
    while ((e = readdir(d)) != NULL) {
        if (!strcmp(e->d_name, ".") || !strcmp(e->d_name, "..")) {
            continue;
        }
        if (cnt >= cap) {
            cap *= 2;
            DirEntry *na = (DirEntry *)realloc(arr, sizeof(DirEntry) * cap);
            if (!na) {
                break;
            }
            arr = na;
        }
        DirEntry *de = &arr[cnt];
        snprintf(de->name, sizeof(de->name), "%s", e->d_name);
        de->is_dir = false;
        de->size = 0;
        de->child_count = 0;
        char full[1024];
        snprintf(full, sizeof(full), "%s/%s", path, e->d_name);
        struct stat st;
        if (stat(full, &st) == 0) {
            de->is_dir = S_ISDIR(st.st_mode);
            de->size = (uint64_t)st.st_size;
            if (de->is_dir) {
                de->child_count = count_dir(full);
            }
        }
        cnt++;
    }
    closedir(d);
    qsort(arr, cnt, sizeof(DirEntry), cmp_entries);
    *out = arr;
    return cnt;
}

static void show_file_detail(const char *name, uint64_t size) {
    char hs[32];
    human_size(size, hs, sizeof(hs));
    while (appletMainLoop()) {
        draw_header("Installed (read-only)");
        printf("\nFile: %s\n\n", name);
        printf("Size: %s (%llu bytes)\n", hs, (unsigned long long)size);
        printf("\nB back\n");
        consoleUpdate(NULL);
        padUpdate(&g_pad);
        if (padGetButtonsDown(&g_pad) & (HidNpadButton_B | HidNpadButton_A)) {
            return;
        }
    }
}

static bool confirm_danger(const char *line1, const char *line2); /* below */
static void view_queue(void);                                      /* below */

/* Directory browser; recurses into subfolders. X deletes the selected entry
 * (file or whole folder) after a confirmation prompt. */
static void browse_dir(const char *path, const char *title) {
    DirEntry *entries = NULL;
    int n = read_dir(path, &entries);
    if (n < 0) {
        draw_header("Installed");
        printf("\nCannot open:\n%s\n", path);
        wait_for_button();
        return;
    }

    int cursor = 0, top = 0, hold = 0;
    const int rows = list_rows();
    int W = con_width();

    while (appletMainLoop()) {
        char sub[96];
        snprintf(sub, sizeof(sub), "Installed: %.40s  (%d/%d)", title,
                 n > 0 ? cursor + 1 : 0, n);
        draw_header(sub);
        if (n == 0) {
            printf(C_CYAN "  (empty)" C_RESET "\n");
        }
        if (cursor < top) {
            top = cursor;
        }
        if (cursor >= top + rows) {
            top = cursor - rows + 1;
        }
        for (int i = top; i < n && i < top + rows; i++) {
            bool sel = (i == cursor);
            if (entries[i].is_dir) {
                if (sel) {
                    char line[128];
                    snprintf(line, sizeof(line), "> [DIR] %-*.*s (%d)", W - 22,
                             W - 22, entries[i].name, entries[i].child_count);
                    hl_row(line);
                } else {
                    printf("  %s[DIR]%s %s%-*.*s%s %s(%d)%s\n", C_CYAN, C_RESET,
                           C_WHITE, W - 22, W - 22, entries[i].name, C_RESET,
                           C_GREEN, entries[i].child_count, C_RESET);
                }
            } else {
                uint64_t sz = entries[i].size;
                char hs[32];
                human_size(sz, hs, sizeof(hs));
                int namew = W - 14;
                if (namew < 10) {
                    namew = 10;
                }
                if (sel) {
                    char line[160];
                    snprintf(line, sizeof(line), "> %-*.*s %10s", namew, namew,
                             entries[i].name, hs);
                    hl_row(line);
                } else {
                    printf("  %-*.*s %s%10s%s\n", namew, namew, entries[i].name,
                           size_color(sz), hs, C_RESET);
                }
            }
        }
        draw_scrollbar(top, n);
        draw_footer("U/D move  ZR page  A open  - delete  ZL queue  L/B back");
        consoleUpdate(NULL);
        applet_sleep_tick();

        padUpdate(&g_pad);
        u64 kd = padGetButtonsDown(&g_pad);
        u64 kh = padGetButtons(&g_pad);
        if (kd & (HidNpadButton_B | HidNpadButton_L)) {
            break; /* L or B goes back up a level */
        }
        if (kd & HidNpadButton_ZL) {
            view_queue(); /* jump to the download queue */
        }
        if (n > 0) {
            int d = nav_repeat(kd, kh, &hold);
            if (d < 0) {
                cursor = (cursor - 1 + n) % n;
            }
            if (d > 0) {
                cursor = (cursor + 1) % n;
            }
            if (kd & HidNpadButton_ZR) {
                cursor += rows;
                if (cursor >= n) {
                    cursor = n - 1;
                }
            }
            if (kd & HidNpadButton_A) {
                if (entries[cursor].is_dir) {
                    char child[1024];
                    snprintf(child, sizeof(child), "%s/%s", path,
                             entries[cursor].name);
                    browse_dir(child, entries[cursor].name);
                } else {
                    show_file_detail(entries[cursor].name, entries[cursor].size);
                }
            }
            if (kd & HidNpadButton_Minus) {
                char l1[160];
                snprintf(l1, sizeof(l1), "Delete \"%.80s\"%s?",
                         entries[cursor].name,
                         entries[cursor].is_dir ? " and ALL its contents" : "");
                if (confirm_danger(l1, "This CANNOT be undone.")) {
                    char full[1024];
                    snprintf(full, sizeof(full), "%s/%s", path,
                             entries[cursor].name);
                    fs_rm_rf(full);
                    toast("Deleted");
                    free(entries);
                    n = read_dir(path, &entries);
                    if (n < 0) {
                        n = 0;
                        entries = NULL;
                    }
                    if (cursor >= n) {
                        cursor = n > 0 ? n - 1 : 0;
                    }
                    top = 0;
                }
            }
        }
    }
    free(entries);
}

static void view_installed(void) {
    browse_dir(ROMS_ROOT, "tico/roms");
}

/* ---- download queue view --------------------------------------------- */

static const char *qstatus_str(QStatus s) {
    switch (s) {
    case Q_QUEUED:      return "wait ";
    case Q_DOWNLOADING: return "dl   ";
    case Q_VERIFYING:   return "vrfy ";
    case Q_EXTRACTING:  return "unzip";
    case Q_DONE:        return "done ";
    case Q_SAVED:       return "saved";
    case Q_FAILED:      return "FAIL ";
    case Q_CANCELLED:   return "cxl  ";
    default:            return "?    ";
    }
}

static const char *qstatus_color(QStatus s) {
    switch (s) {
    case Q_DOWNLOADING: return C_CYAN;
    case Q_VERIFYING:   return C_YELLOW;
    case Q_EXTRACTING:  return C_YELLOW;
    case Q_DONE:        return C_GREEN;
    case Q_SAVED:       return C_YELLOW;
    case Q_FAILED:      return C_RED;
    default:            return ""; /* wait / cancelled */
    }
}

static void view_queue(void) {
    static QueueView qv[QUEUE_MAX];
    int cursor = 0, top = 0, hold = 0;
    const int rows = list_rows();

    while (appletMainLoop()) {
        int n = queue_snapshot(qv, QUEUE_MAX);
        if (cursor >= n) {
            cursor = n > 0 ? n - 1 : 0;
        }
        char qsub[48];
        snprintf(qsub, sizeof(qsub), "Download Queue  (%d/%d)",
                 n > 0 ? cursor + 1 : 0, n);
        draw_header(qsub);
        if (n == 0) {
            printf(C_CYAN "  Queue empty - press A on a file in a console list "
                          "to add it." C_RESET "\n");
        }
        if (cursor < top) {
            top = cursor;
        }
        if (cursor >= top + rows) {
            top = cursor - rows + 1;
        }
        int namew = con_width() - 47; /* marker+status+console+info+speed columns */
        if (namew < 8) {
            namew = 8;
        }
        for (int i = top; i < n && i < top + rows; i++) {
            const QueueItem *it = &qv[i].item;
            bool sel = (i == cursor);
            char info[24] = "";
            char spd[20] = "";
            char ts[16];
            if (it->status == Q_DOWNLOADING && it->total) {
                human_size(it->total, ts, sizeof(ts));
                snprintf(info, sizeof(info), "%d%% / %s",
                         (int)((it->now * 100) / it->total), ts);
                if (it->speed) {
                    char hs[16];
                    human_size(it->speed, hs, sizeof(hs));
                    snprintf(spd, sizeof(spd), "%s/s", hs);
                }
            } else if (it->total) {
                human_size(it->total, ts, sizeof(ts));
                snprintf(info, sizeof(info), "%s", ts);
            }
            if (sel) {
                char line[256];
                snprintf(line, sizeof(line), "> %s [%-8.8s] %-*.*s %-16s %-9s",
                         qstatus_str(it->status), it->target, namew, namew,
                         it->name, info, spd);
                hl_row(line);
            } else {
                printf("  %s%s%s [%-8.8s] %-*.*s %s%-16s%s %s%-9s%s\n",
                       qstatus_color(it->status), qstatus_str(it->status),
                       C_RESET, it->target, namew, namew, it->name, C_CYAN, info,
                       C_RESET, C_GREEN, spd, C_RESET);
            }
        }
        draw_scrollbar(top, n);
        draw_footer("U/D move  A cancel  X retry  Y clear finished  B back");
        consoleUpdate(NULL);
        applet_sleep_tick();

        padUpdate(&g_pad);
        u64 kd = padGetButtonsDown(&g_pad);
        u64 kh = padGetButtons(&g_pad);
        if (kd & HidNpadButton_B) {
            return;
        }
        if (kd & HidNpadButton_Y) {
            queue_clear_finished();
            toast("Cleared finished");
        }
        if (n > 0) {
            int d = nav_repeat(kd, kh, &hold);
            if (d < 0) {
                cursor = (cursor - 1 + n) % n;
            }
            if (d > 0) {
                cursor = (cursor + 1) % n;
            }
            if (kd & HidNpadButton_A) {
                queue_cancel(qv[cursor].slot);
                toast("Cancelled");
            }
            if (kd & HidNpadButton_X) {
                queue_retry(qv[cursor].slot);
                toast("Retrying");
            }
        }
    }
}

/* ---- editors --------------------------------------------------------- */

/* Yes/No confirmation screen. Returns true if the user pressed A. */
static bool confirm(const char *line1, const char *line2) {
    while (appletMainLoop()) {
        draw_header(NULL);
        printf("\n%s\n", line1);
        if (line2) {
            printf("%s\n", line2);
        }
        printf("\nA = Yes      B = No\n");
        consoleUpdate(NULL);
        padUpdate(&g_pad);
        u64 k = padGetButtonsDown(&g_pad);
        if (k & HidNpadButton_A) {
            return true;
        }
        if (k & HidNpadButton_B) {
            return false;
        }
    }
    return false;
}

/* Confirmation for destructive actions: the selection defaults to "No" and the
 * user must move to "Yes" before A confirms, so a stray A-press can't delete. */
static bool confirm_danger(const char *line1, const char *line2) {
    int sel = 0; /* 0 = No (default), 1 = Yes */
    while (appletMainLoop()) {
        draw_header(NULL);
        printf("\n%s\n", line1);
        if (line2) {
            printf(C_YELLOW "%s" C_RESET "\n", line2);
        }
        printf("\n   %s    %s\n",
               sel == 1 ? C_ERR " YES " C_RESET : "  Yes ",
               sel == 0 ? C_SEL "[ NO ]" C_RESET : "  No ");
        printf("\nLeft/Right choose   A confirm   B cancel\n");
        consoleUpdate(NULL);
        padUpdate(&g_pad);
        u64 k = padGetButtonsDown(&g_pad);
        if (k & HidNpadButton_AnyLeft) {
            sel = 1;
        }
        if (k & HidNpadButton_AnyRight) {
            sel = 0;
        }
        if (k & HidNpadButton_B) {
            return false;
        }
        if (k & HidNpadButton_A) {
            return sel == 1;
        }
    }
    return false;
}

/* Edit one repo's fields (label / archive id / URL / active), or delete it. */
static void repo_editor(int ci, int ri) {
    while (appletMainLoop()) {
        if (ci < 0 || ci >= g_cfg.console_count) {
            return;
        }
        ConsoleGroup *g = &g_cfg.consoles[ci];
        if (ri < 0 || ri >= g->repo_count) {
            return;
        }
        Repo *rp = &g->repos[ri];
        char sub[80];
        snprintf(sub, sizeof(sub), "Edit repo  (%s)", g->console);
        draw_header(sub);
        printf("Name           : %s\n", rp->label[0] ? rp->label : "<unset>");
        printf("Archive.org ID : %s\n", rp->id[0] ? rp->id : "<unset>");
        printf("Download URL   : %s\n",
               rp->download_base[0] ? rp->download_base : "<auto>");
        printf("Enabled        : %s\n", rp->enabled ? "yes" : "no");
        printf("\nA set ID   X set name   Y toggle enabled\n");
        printf("ZL set URL   (-) delete   B back\n");
        draw_footer("A id  X name  Y enable  ZL url  - delete  B back");
        consoleUpdate(NULL);
        applet_sleep_tick();

        padUpdate(&g_pad);
        u64 k = padGetButtonsDown(&g_pad);
        if (k & HidNpadButton_B) {
            return;
        }
        if (k & HidNpadButton_A) {
            char v[256] = {0};
            if (prompt_text("archive.org item id", rp->id, v, sizeof(v))) {
                snprintf(rp->id, sizeof(rp->id), "%s", v);
                rp->download_base[0] = '\0';
                repo_set_url_default(rp);
                config_save(&g_cfg);
                toast("Saved");
            }
        }
        if (k & HidNpadButton_X) {
            char v[64] = {0};
            if (prompt_text("Repo name", rp->label, v, sizeof(v))) {
                snprintf(rp->label, sizeof(rp->label), "%s", v);
                config_save(&g_cfg);
                toast("Saved");
            }
        }
        if (k & HidNpadButton_Y) {
            rp->enabled = !rp->enabled;
            config_save(&g_cfg);
            toast("Repo %s", rp->enabled ? "enabled" : "disabled");
        }
        if (k & HidNpadButton_ZL) {
            char v[512] = {0};
            if (prompt_text("Download base URL", rp->download_base, v,
                            sizeof(v))) {
                snprintf(rp->download_base, sizeof(rp->download_base), "%s", v);
                config_save(&g_cfg);
                toast("Saved");
            }
        }
        if (k & HidNpadButton_Minus) {
            if (confirm_danger("Delete this repo?", "This cannot be undone.")) {
                config_remove_repo(g, ri);
                config_save(&g_cfg);
                toast("Deleted repo");
                return;
            }
        }
    }
}

/* Grouped view: a console's repo list. Browse, edit, add or delete repos. */
static void open_console(int ci) {
    int cursor = 0, top = 0, hold = 0;
    const int rows = list_rows();
    while (appletMainLoop()) {
        if (ci < 0 || ci >= g_cfg.console_count) {
            return;
        }
        ConsoleGroup *g = &g_cfg.consoles[ci];
        int n = g->repo_count;
        MenuRef refs[MAX_REPOS];
        for (int r = 0; r < n; r++) {
            refs[r].ci = ci;
            refs[r].ri = r;
        }
        char sub[80];
        snprintf(sub, sizeof(sub), "%s  (%d/%d repos)", g->console,
                 n > 0 ? cursor + 1 : 0, n);
        draw_header(sub);
        if (n == 0) {
            printf(C_CYAN "  No repos yet. Press Y to add one." C_RESET "\n");
        }
        if (cursor >= n) {
            cursor = n > 0 ? n - 1 : 0;
        }
        if (cursor < top) {
            top = cursor;
        }
        if (cursor >= top + rows) {
            top = cursor - rows + 1;
        }
        int W = con_width();
        for (int i = top; i < n && i < top + rows; i++) {
            bool sel = (i == cursor);
            Repo *rp = &g->repos[i];
            if (sel) {
                char line[128];
                snprintf(line, sizeof(line), "> [%-3s] %-*.*s",
                         rp->enabled ? "on" : "off", W - 9, W - 9, rp->label);
                hl_row(line);
            } else {
                printf("  %s[%-3s]%s %-*.*s\n", rp->enabled ? C_GREEN : "",
                       rp->enabled ? "on" : "off", C_RESET, W - 9, W - 9,
                       rp->label);
            }
        }
        draw_scrollbar(top, n);
        draw_footer("A browse  X edit  Y add repo  - del repo  B back");
        consoleUpdate(NULL);
        applet_sleep_tick();

        padUpdate(&g_pad);
        u64 kd = padGetButtonsDown(&g_pad);
        u64 kh = padGetButtons(&g_pad);
        if (kd & HidNpadButton_B) {
            return;
        }
        if (kd & HidNpadButton_Y) {
            char lbl[64] = {0}, id[256] = {0};
            if (prompt_text("Repo name (e.g. No-Intro)", NULL, lbl,
                            sizeof(lbl)) &&
                prompt_text("archive.org item id", NULL, id, sizeof(id))) {
                if (config_add_repo(g, lbl, id)) {
                    config_save(&g_cfg);
                    toast("Added repo: %.40s", lbl);
                } else {
                    toast_error("Console is full");
                }
            }
            continue;
        }
        if (n > 0) {
            int d = nav_repeat(kd, kh, &hold);
            if (d < 0) {
                cursor = (cursor - 1 + n) % n;
            }
            if (d > 0) {
                cursor = (cursor + 1) % n;
            }
            if (kd & HidNpadButton_A) {
                browse_repo_refs(refs, n, cursor);
            }
            if (kd & HidNpadButton_X) {
                repo_editor(ci, cursor);
            }
            if (kd & HidNpadButton_Minus) {
                if (confirm_danger("Delete this repo?",
                                   "This cannot be undone.")) {
                    config_remove_repo(g, cursor);
                    config_save(&g_cfg);
                    toast("Deleted repo");
                }
            }
        }
    }
}

/* Copy src over dst by truncating dst in place (fopen "wb") rather than
 * deleting it first — safer for replacing the currently-running .nro. On
 * failure *err gets errno. */
static bool install_over(const char *src, const char *dst, int *err) {
    *err = 0;
    FILE *in = fopen(src, "rb");
    if (!in) {
        *err = errno;
        return false;
    }
    FILE *out = fopen(dst, "wb");
    if (!out) {
        *err = errno;
        fclose(in);
        return false;
    }
    char buf[65536];
    size_t r;
    bool ok = true;
    while ((r = fread(buf, 1, sizeof(buf), in)) > 0) {
        if (fwrite(buf, 1, r, out) != r) {
            *err = errno;
            ok = false;
            break;
        }
    }
    fclose(in);
    if (fclose(out) != 0 && ok) {
        *err = errno;
        ok = false;
    }
    return ok;
}

/* Check GitHub for a newer release and, if the user confirms, download it and
 * overwrite our own .nro on the SD card. */
static void run_update(void) {
    draw_header("Update");
    printf("Current : %s\n", APP_VERSION_STR);
    printf("Repo    : %s\n", UPDATE_REPO);
    printf("\nChecking for the latest release...\n");
    consoleUpdate(NULL);

    char tag[64], url[1024];
    if (!update_fetch_latest(UPDATE_REPO, tag, sizeof(tag), url, sizeof(url))) {
        printf("\nCould not fetch release info.\n");
        printf("(Check UPDATE_REPO, network, or that a release with an\n");
        printf(" attached .nro exists.)\n");
        wait_for_button();
        return;
    }

    printf("Latest  : %s\n", tag);
    if (version_cmp(APP_VERSION_STR, tag) >= 0) {
        printf("\nYou are up to date (v%s).\n", APP_VERSION_STR);
        wait_for_button();
        return;
    }

    char prompt[96];
    snprintf(prompt, sizeof(prompt), "Update to %s now?", tag);
    if (!confirm(prompt, "Downloads and replaces this app.")) {
        return;
    }

    char dl[1024];
    snprintf(dl, sizeof(dl), "%s/downloads/update.nro", CONFIG_DIR);
    fs_ensure_parent(dl);

    char usub[80];
    snprintf(usub, sizeof(usub), "Update -> %s", tag);
    draw_header(usub);
    printf("\n");
    consoleUpdate(NULL);

    struct prog_state ps = {-1};
    long code = 0;
    if (!http_download(url, dl, NULL, progress_cb, &ps, 0, &code)) {
        remove(dl);
        printf("\nDownload failed (http %ld).\n", code);
        wait_for_button();
        return;
    }

    /* libnx keeps the running .nro open to serve its embedded romfs, which locks
     * the file and makes overwriting it fail with an I/O error. Close romfs
     * first, do the swap, then re-open it so the session keeps working. */
    romfsExit();

    char prev[1100];
    snprintf(prev, sizeof(prev), "%s.previous", g_self_path);
    int berr = 0;
    install_over(g_self_path, prev, &berr); /* best-effort backup */

    int err = 0;
    bool ok = install_over(dl, g_self_path, &err);

    romfsInit();

    if (!ok) {
        printf("\nInstall failed (%s):\n%s\n", strerror(err), g_self_path);
        printf("\nThe new build was kept here so you can copy it manually:\n%s\n",
               dl);
        wait_for_button();
        return;
    }
    remove(dl);

    printf("\nUpdated to %s.\n", tag);
    printf("Close TicoDL+ and relaunch to use the new version.\n");
    printf("(Backup kept at %s)\n", prev);
    wait_for_button();
}

/* Read-only viewer for the download history log (newest first). */
static void view_log(void) {
    size_t len = 0;
    char *buf = json_read_file(DLLOG_PATH, &len);
    static char *lines[4000];
    int nl = 0;
    if (buf) {
        char *p = buf;
        while (*p && nl < 4000) {
            lines[nl++] = p;
            char *e = strchr(p, '\n');
            if (!e) {
                break;
            }
            *e = '\0';
            p = e + 1;
        }
    }

    int cursor = 0, top = 0, hold = 0;
    const int rows = list_rows();
    int W = con_width();

    while (appletMainLoop()) {
        char lsub[48];
        snprintf(lsub, sizeof(lsub), "Download Log  (%d/%d)",
                 nl > 0 ? cursor + 1 : 0, nl);
        draw_header(lsub);
        if (nl == 0) {
            printf(C_CYAN "  No downloads logged yet." C_RESET "\n");
        }
        if (cursor < top) {
            top = cursor;
        }
        if (cursor >= top + rows) {
            top = cursor - rows + 1;
        }
        for (int i = top; i < nl && i < top + rows; i++) {
            int idx = nl - 1 - i; /* newest first */
            if (i == cursor) {
                char line[256];
                snprintf(line, sizeof(line), "> %-*.*s", W - 3, W - 3,
                         lines[idx]);
                hl_row(line);
            } else {
                printf("  %-.*s\n", W - 3, lines[idx]);
            }
        }
        draw_scrollbar(top, nl);
        draw_footer("Up/Down scroll   ZL/ZR page   B back");
        consoleUpdate(NULL);
        applet_sleep_tick();

        padUpdate(&g_pad);
        u64 kd = padGetButtonsDown(&g_pad);
        u64 kh = padGetButtons(&g_pad);
        if (kd & HidNpadButton_B) {
            break;
        }
        if (nl > 0) {
            int d = nav_repeat(kd, kh, &hold);
            if (d < 0) {
                cursor = (cursor - 1 + nl) % nl;
            }
            if (d > 0) {
                cursor = (cursor + 1) % nl;
            }
            if (kd & HidNpadButton_ZL) {
                cursor -= rows;
                if (cursor < 0) {
                    cursor = 0;
                }
            }
            if (kd & HidNpadButton_ZR) {
                cursor += rows;
                if (cursor >= nl) {
                    cursor = nl - 1;
                }
            }
        }
    }
    free(buf);
}

static void manual_url(void); /* defined below; reached from Settings */

/* Navigable settings: D-pad to move, A to toggle/open, B to exit. Changes are
 * saved the moment they're made. */
static void edit_settings(void) {
    const int N = 9;
    int cursor = 0, hold = 0;

    while (appletMainLoop()) {
        char sub[48];
        snprintf(sub, sizeof(sub), "Settings   (v%s)", APP_VERSION_STR);
        draw_header(sub);

        static const char *labels[9] = {
            "Metadata cache",         "Stay awake while downloading",
            "Group consoles",         "Archive.org access key",
            "Archive.org secret",     "Check for updates",
            "View download log",      "Download from URL",
            "Credits"};
        char vals[9][64];
        snprintf(vals[0], 64, "%s", g_prefs.use_cache ? "ON" : "OFF");
        snprintf(vals[1], 64, "%s", g_prefs.prevent_sleep ? "ON" : "OFF");
        snprintf(vals[2], 64, "%s", g_prefs.group_consoles ? "ON" : "OFF");
        snprintf(vals[3], 64, "%.63s",
                 g_creds.access_key[0] ? g_creds.access_key : "<unset>");
        snprintf(vals[4], 64, "%s", g_creds.secret[0] ? "<set>" : "<unset>");
        snprintf(vals[5], 64, "v%s", APP_VERSION_STR);
        vals[6][0] = '\0';
        snprintf(vals[7], 64, "%s", "paste a link");
        snprintf(vals[8], 64, "%s", "created by digdat0");

        for (int i = 0; i < N; i++) {
            if (i == cursor) {
                char line[128];
                snprintf(line, sizeof(line), "> %-28.28s %.63s", labels[i],
                         vals[i]);
                hl_row(line);
            } else {
                const char *vc = (strcmp(vals[i], "ON") == 0) ? C_GREEN : C_CYAN;
                printf("  %-28s %s%s%s\n", labels[i], vals[i][0] ? vc : "",
                       vals[i], C_RESET);
            }
        }

        draw_footer("Up/Down move   A select/toggle   B back");
        consoleUpdate(NULL);
        applet_sleep_tick();

        padUpdate(&g_pad);
        u64 k = padGetButtonsDown(&g_pad);
        u64 kh = padGetButtons(&g_pad);
        if (k & HidNpadButton_B) {
            return;
        }
        int d = nav_repeat(k, kh, &hold);
        if (d < 0) {
            cursor = (cursor - 1 + N) % N;
        }
        if (d > 0) {
            cursor = (cursor + 1) % N;
        }
        if (k & HidNpadButton_A) {
            char v[128] = {0};
            switch (cursor) {
            case 0:
                g_prefs.use_cache = !g_prefs.use_cache;
                prefs_save(&g_prefs);
                toast("Metadata cache %s", g_prefs.use_cache ? "ON" : "OFF");
                break;
            case 1:
                g_prefs.prevent_sleep = !g_prefs.prevent_sleep;
                prefs_save(&g_prefs);
                toast("Stay awake %s", g_prefs.prevent_sleep ? "ON" : "OFF");
                break;
            case 2:
                g_prefs.group_consoles = !g_prefs.group_consoles;
                prefs_save(&g_prefs);
                toast("Grouping %s", g_prefs.group_consoles ? "ON" : "OFF");
                break;
            case 3:
                if (prompt_text("Access Key", g_creds.access_key, v,
                                sizeof(v))) {
                    snprintf(g_creds.access_key, sizeof(g_creds.access_key),
                             "%s", v);
                    creds_save(&g_creds);
                    toast("Access key saved");
                }
                break;
            case 4:
                if (prompt_text("Secret Key", NULL, v, sizeof(v))) {
                    snprintf(g_creds.secret, sizeof(g_creds.secret), "%s", v);
                    creds_save(&g_creds);
                    toast("Secret saved");
                }
                break;
            case 5:
                run_update();
                break;
            case 6:
                view_log();
                break;
            case 7:
                manual_url();
                break;
            default:
                break;
            }
        }
    }
}

/* Pick a TICO-supported console from the master list. Returns the chosen name
 * (a pointer into g_cfg.supported) or NULL if cancelled. */
static const char *pick_console(void) {
    int cursor = 0, top = 0, hold = 0;
    const int rows = list_rows();
    while (appletMainLoop()) {
        int n = g_cfg.supported_count;
        char psub[48];
        snprintf(psub, sizeof(psub), "Select console  (%d/%d)",
                 n > 0 ? cursor + 1 : 0, n);
        draw_header(psub);
        if (n == 0) {
            printf(C_CYAN
                   "  No supported consoles in dl_sources.json (tico_consoles)."
                   C_RESET "\n");
        }
        if (cursor >= n) {
            cursor = n > 0 ? n - 1 : 0;
        }
        if (cursor < top) {
            top = cursor;
        }
        if (cursor >= top + rows) {
            top = cursor - rows + 1;
        }
        for (int i = top; i < n && i < top + rows; i++) {
            bool sel = (i == cursor);
            ConsoleGroup *g = config_find_console(&g_cfg, g_cfg.supported[i]);
            if (sel) {
                char line[96];
                snprintf(line, sizeof(line), "> %-16.16s (%d repos)",
                         g_cfg.supported[i], g ? g->repo_count : 0);
                hl_row(line);
            } else {
                printf("  %-16.16s %s(%d repos)%s\n", g_cfg.supported[i], C_CYAN,
                       g ? g->repo_count : 0, C_RESET);
            }
        }
        draw_scrollbar(top, n);
        draw_footer("U/D move  A select  B cancel");
        consoleUpdate(NULL);
        applet_sleep_tick();
        padUpdate(&g_pad);
        u64 kd = padGetButtonsDown(&g_pad);
        u64 kh = padGetButtons(&g_pad);
        if (kd & HidNpadButton_B) {
            return NULL;
        }
        if (n > 0) {
            int d = nav_repeat(kd, kh, &hold);
            if (d < 0) {
                cursor = (cursor - 1 + n) % n;
            }
            if (d > 0) {
                cursor = (cursor + 1) % n;
            }
            if (kd & HidNpadButton_A) {
                return g_cfg.supported[cursor];
            }
        }
    }
    return NULL;
}

static void manual_url(void) {
    char input[1024] = {0};
    if (!prompt_text("archive.org URL or item id", NULL, input,
                     sizeof(input))) {
        return;
    }
    char id[256];
    if (!ia_extract_id(input, id, sizeof(id))) {
        draw_header(NULL);
        printf("\nCould not parse an item id.\n");
        wait_for_button();
        return;
    }
    const char *cname = pick_console();
    if (!cname) {
        return;
    }
    char target[64];
    snprintf(target, sizeof(target), "%s", cname);
    draw_header(NULL);
    printf("\nFetching metadata for %s...\n", id);
    consoleUpdate(NULL);

    ArchiveItem item;
    if (!ia_fetch(id, &item, g_prefs.use_cache, CACHE_DIR)) {
        printf("Metadata fetch failed or item has no files.\n");
        wait_for_button();
        return;
    }
    char crumb[96];
    snprintf(crumb, sizeof(crumb), "URL > %s", target);
    browse_item(&item, target, crumb);
    ia_free(&item);
}

/* ---- main menu ------------------------------------------------------- */

/* Full controls reference, opened with ZR from the main menu. */
static void show_help(void) {
    while (appletMainLoop()) {
        draw_header("Controls / Help");
        printf("\n");
        printf("    A = open/confirm   B = back   X = edit   Y = add   "
               "- = delete\n\n");
        printf(C_YELLOW
               "  TicoDL+ ships no collections. Add your own: press Y and\n"
               "  enter an archive.org item id." C_RESET "\n\n");
        printf(C_CYAN "  Main menu\n" C_RESET);
        printf("    grouped: A open console   - del console   Y add repo\n");
        printf("    flat:    A browse repo    X edit repo     Y add repo\n");
        printf("    Y picks a supported console (from dl_sources.json)\n");
        printf("    ZL queue   R installed   L settings   ZR help   + exit\n\n");
        printf(C_CYAN "  Console screen (grouped)\n" C_RESET);
        printf("    A browse repo  X edit repo  Y add repo  - del repo\n\n");
        printf(C_CYAN "  Browsing files\n" C_RESET);
        printf("    U/D move  ZL/ZR page  L/R switch repo  A queue\n");
        printf("    Y filter  X refresh  B back   "
               C_GREEN "*" C_RESET " = installed\n\n");
        printf(C_CYAN "  Queue (ZL): A cancel  X retry  Y clear  B back\n"
                      C_RESET);
        printf(C_CYAN "  Installed (R): A open  - delete  ZL queue  L/B back\n"
                      C_RESET);
        printf("    (manual URL download is in Settings)\n\n");
        printf(C_CYAN "  Colors\n" C_RESET);
        printf("    size " C_GREEN "KB" C_RESET " " C_YELLOW "MB" C_RESET " "
               C_RED "GB" C_RESET "    " C_GREEN "*" C_RESET " installed    "
               "queue " C_CYAN "dl" C_RESET " " C_YELLOW "unzip" C_RESET " "
               C_GREEN "done" C_RESET " " C_RED "FAIL" C_RESET "\n");
        draw_footer("B / ZR  back");
        consoleUpdate(NULL);
        applet_sleep_tick();
        padUpdate(&g_pad);
        u64 k = padGetButtonsDown(&g_pad);
        if (k & (HidNpadButton_B | HidNpadButton_ZR)) {
            return;
        }
    }
}

/* The main list, rebuilt each frame: grouped = one entry per console, flat = one
 * entry per repo. */
static MenuRef g_menu[MAX_CONSOLES * MAX_REPOS];

static int build_menu(void) {
    int cap = (int)(sizeof(g_menu) / sizeof(g_menu[0]));
    int n = 0;
    if (g_prefs.group_consoles) {
        for (int c = 0; c < g_cfg.console_count && n < cap; c++) {
            g_menu[n].ci = c;
            g_menu[n].ri = -1;
            n++;
        }
    } else {
        for (int c = 0; c < g_cfg.console_count; c++) {
            for (int r = 0; r < g_cfg.consoles[c].repo_count && n < cap; r++) {
                g_menu[n].ci = c;
                g_menu[n].ri = r;
                n++;
            }
        }
    }
    return n;
}

static void draw_menu(int cursor, int top, int rows, int n) {
    char sub[48];
    snprintf(sub, sizeof(sub), "%s  (%d/%d)",
             g_prefs.group_consoles ? "Consoles" : "Repos", n > 0 ? cursor + 1 : 0,
             n);
    draw_header(sub);

    if (n == 0) {
        printf(C_CYAN
               "  No collections yet. Press Y to add one\n"
               "  (you provide the archive.org item id)." C_RESET "\n");
    }
    int W = con_width();
    for (int i = top; i < n && i < top + rows; i++) {
        bool sel = (i == cursor);
        ConsoleGroup *g = &g_cfg.consoles[g_menu[i].ci];
        if (g_menu[i].ri < 0) {
            /* grouped: one row per console */
            if (sel) {
                char line[96];
                snprintf(line, sizeof(line), "> %-16.16s (%d repos)", g->console,
                         g->repo_count);
                hl_row(line);
            } else {
                printf("  %s%-16.16s%s %s(%d repos)%s\n", C_WHITE, g->console,
                       C_RESET, C_CYAN, g->repo_count, C_RESET);
            }
        } else {
            /* flat: one row per repo, "target - label" */
            Repo *rp = &g->repos[g_menu[i].ri];
            char name[96];
            snprintf(name, sizeof(name), "%s - %s", g->target, rp->label);
            if (sel) {
                char line[128];
                snprintf(line, sizeof(line), "> [%-3s] %-*.*s",
                         rp->enabled ? "on" : "off", W - 9, W - 9, name);
                hl_row(line);
            } else {
                printf("  %s[%-3s]%s %s%-*.*s%s\n", rp->enabled ? C_GREEN : "",
                       rp->enabled ? "on" : "off", C_RESET, C_WHITE, W - 9,
                       W - 9, name, C_RESET);
            }
        }
    }
    draw_scrollbar(top, n);
    if (g_prefs.group_consoles) {
        draw_footer("A open  Y add repo  - del console  ZL queue  R installed  "
                    "L settings  ZR help  +exit");
    } else {
        draw_footer("A browse  X edit  Y add repo  - del repo  ZL queue  "
                    "R install  L settings  ZR help  +exit");
    }
    consoleUpdate(NULL);
}

/* Add a repo: pick a supported console, then enter its label + archive id. */
static void add_repo_flow(void) {
    const char *cname = pick_console();
    if (!cname) {
        return;
    }
    char lbl[64] = {0}, id[256] = {0};
    if (prompt_text("Repo name (e.g. No-Intro)", NULL, lbl, sizeof(lbl)) &&
        prompt_text("archive.org item id", NULL, id, sizeof(id))) {
        ConsoleGroup *g = config_add_console(&g_cfg, cname);
        if (g && config_add_repo(g, lbl, id)) {
            config_sort(&g_cfg); /* keep the console list A-Z */
            config_save(&g_cfg);
            toast("Added %.30s to %s", lbl, cname);
        } else {
            toast_error("Couldn't add repo (full?)");
        }
    }
}

int main(int argc, char **argv) {
    /* hbloader passes our own .nro path as argv[0]; fall back to the default. */
    if (argc > 0 && argv[0] && strstr(argv[0], ".nro")) {
        snprintf(g_self_path, sizeof(g_self_path), "%s", argv[0]);
    } else {
        snprintf(g_self_path, sizeof(g_self_path), "%s", DEFAULT_SELF_PATH);
    }

    consoleInit(NULL);
    padConfigureInput(1, HidNpadStyleSet_NpadStandard);
    padInitializeDefault(&g_pad);
    romfsInit();
    psmInitialize(); /* battery readout in the header (best-effort) */

    if (!net_init()) {
        printf("Network init failed.\n");
        consoleUpdate(NULL);
    }

    config_load(&g_cfg);
    config_sort(&g_cfg);
    creds_load(&g_creds);
    prefs_load(&g_prefs);
    queue_init();

    int cursor = 0;
    int top = 0;
    int hold = 0;
    const int rows = list_rows();

    while (appletMainLoop()) {
        int n = build_menu();
        if (cursor >= n) {
            cursor = n > 0 ? n - 1 : 0;
        }
        if (cursor < top) {
            top = cursor;
        }
        if (cursor >= top + rows) {
            top = cursor - rows + 1;
        }
        draw_menu(cursor, top, rows, n);
        applet_sleep_tick();

        padUpdate(&g_pad);
        u64 k = padGetButtonsDown(&g_pad);
        u64 kh = padGetButtons(&g_pad);

        if (k & HidNpadButton_Plus) {
            break;
        }
        if (k & HidNpadButton_ZL) {
            view_queue();
            continue;
        }
        if (k & HidNpadButton_ZR) {
            show_help();
            continue;
        }
        if (k & HidNpadButton_L) {
            edit_settings();
            continue;
        }
        if (k & HidNpadButton_R) {
            view_installed();
            continue;
        }
        if (k & HidNpadButton_Y) {
            add_repo_flow(); /* pick a supported console, then add a repo */
            continue;
        }

        if (n == 0) {
            continue;
        }
        int d = nav_repeat(k, kh, &hold);
        if (d < 0) {
            cursor = (cursor - 1 + n) % n;
        }
        if (d > 0) {
            cursor = (cursor + 1) % n;
        }
        MenuRef ref = g_menu[cursor];
        if (k & HidNpadButton_A) {
            if (ref.ri < 0) {
                open_console(ref.ci); /* grouped: show this console's repos */
            } else {
                browse_repo_refs(g_menu, n, cursor); /* flat: browse this repo */
            }
        }
        if ((k & HidNpadButton_X) && !g_prefs.group_consoles) {
            repo_editor(ref.ci, ref.ri); /* flat: edit the selected repo */
        }
        if (k & HidNpadButton_Minus) {
            if (g_prefs.group_consoles) {
                char msg[96];
                snprintf(msg, sizeof(msg),
                         "Delete console '%s' and all its repos?",
                         g_cfg.consoles[ref.ci].console);
                if (confirm_danger(msg, "This cannot be undone.")) {
                    config_remove_console(&g_cfg, ref.ci);
                    config_save(&g_cfg);
                    toast("Deleted console");
                }
            } else {
                if (confirm_danger("Delete this repo?",
                                   "This cannot be undone.")) {
                    config_remove_repo(&g_cfg.consoles[ref.ci], ref.ri);
                    config_save(&g_cfg);
                    toast("Deleted repo");
                }
            }
        }
    }

    queue_exit();
    appletSetMediaPlaybackState(false);
    net_exit();
    psmExit();
    romfsExit();
    consoleExit(NULL);
    return 0;
}
